# @package _group_
raw_data_path: ${main.raw_data_path}
report_dir: ${main.eda_dir}
report_file_name: "eda_pandas_profiling.html"
report_class:
  _target_: pandas_profiling.ProfileReport
  title: "Pandas Profiling Report"
  explorative: True