apiVersion: v1
kind: Pod
metadata:
  name: online-inference-resources
  labels:
    app: online-inference
spec:
  containers:
    - image: hherasimchyk/online_inference:v1
      name: online-inference
      ports:
        - containerPort: 8000
      resources:
        requests:
          memory: "512Mi"
          cpu: "300m"
        limits:
          memory: "1Gi"
          cpu: "500m"